# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk
# netaddr

- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
    - name: 'Create the Control Plane ports'
      openstack.cloud.port:
        name: "{{ item.port_name }}"
        network: "{{ os_network }}"
        security_groups:
        - "{{ os_sg_master }}"
        fixed_ips:
          - ip_address: "{{ item.ip_address }}"
        allowed_address_pairs:
          - ip_address: "{{ os_apiVIP }}"
          - ip_address: "{{ os_ingressVIP }}"
      loop: "{{ control_plane_hosts }}"

    - name: 'Create the Control Plane servers'
      openstack.cloud.server:
        name: "{{ item.server_name }}"
        image: "{{ os_image_rhcos }}"
        flavor: "{{ os_flavor_master }}"
        auto_ip: no
        userdata: "{{ lookup('file', item.ignition) | string }}"
        nics:
        - port-name: "{{ item.port_name }}"
        availability_zone: "{{ item.az }}"
        boot_from_volume: true
        volume_size: "{{ master_volume_size }}"
      loop: "{{ control_plane_hosts }}"
