# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk
# netaddr

- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
    - name: 'Create the Control Plane port 0'
      os_port:
        name: "{{ os_port_master}}-0"
        network: "{{ os_network }}"
        security_groups:
        - "{{ os_sg_master }}"
        fixed_ips:
          - ip_address: "{{ os_subnet_range | next_nth_usable(20) }}"
        allowed_address_pairs:
          - ip_address: "{{ os_apiVIP }}"
          - ip_address: "{{ os_ingressVIP }}"

    - name: 'Create the Control Plane port 1'
      os_port:
        name: "{{ os_port_master}}-1"
        network: "{{ os_network }}"
        security_groups:
        - "{{ os_sg_master }}"
        fixed_ips:
          - ip_address: "{{ os_subnet_range | next_nth_usable(21) }}"
        allowed_address_pairs:
          - ip_address: "{{ os_apiVIP }}"
          - ip_address: "{{ os_ingressVIP }}"

    - name: 'Create the Control Plane port 2'
      os_port:
        name: "{{ os_port_master}}-2"
        network: "{{ os_network }}"
        security_groups:
        - "{{ os_sg_master }}"
        fixed_ips:
          - ip_address: "{{ os_subnet_range | next_nth_usable(22) }}"
        allowed_address_pairs:
          - ip_address: "{{ os_apiVIP }}"
          - ip_address: "{{ os_ingressVIP }}"


          #  - name: 'Create the Control Plane ports'
          #    os_port:
          #      name: "{{ item.1 }}-{{ item.0 }}"
          #      network: "{{ os_network }}"
          #      security_groups:
          #      - "{{ os_sg_master }}"
          #      allowed_address_pairs:
          #      - ip_address: "{{ os_apiVIP }}"
          #      - ip_address: "{{ os_ingressVIP }}"
          #    with_indexed_items: "{{ [os_port_master] * os_cp_nodes_number }}"
          #    register: ports

    - name: 'Create the Control Plane server 0'
      os_server:
        name: "{{ os_cp_server_name }}-0"
        image: "{{ os_image_rhcos }}"
        flavor: "{{ os_flavor_master }}"
        auto_ip: no
        userdata: "{{ lookup('file', os_master_0_ignition) | string }}"
        nics:
        - port-name: "{{ os_port_master }}-0"
        availability_zone: eu-de-01
        boot_from_volume: true
        volume_size: "{{ master_volume_size }}"

    - name: 'Create the Control Plane server 1'
      os_server:
        name: "{{ os_cp_server_name }}-1"
        image: "{{ os_image_rhcos }}"
        flavor: "{{ os_flavor_master }}"
        auto_ip: no
        userdata: "{{ lookup('file', os_master_1_ignition) | string }}"
        nics:
        - port-name: "{{ os_port_master }}-1"
        availability_zone: eu-de-02
        boot_from_volume: true
        volume_size: "{{ master_volume_size }}"

    - name: 'Create the Control Plane server 2'
      os_server:
        name: "{{ os_cp_server_name }}-2"
        image: "{{ os_image_rhcos }}"
        flavor: "{{ os_flavor_master }}"
        auto_ip: no
        userdata: "{{ lookup('file', os_master_2_ignition) | string }}"
        nics:
        - port-name: "{{ os_port_master }}-2"
        availability_zone: eu-de-03
        boot_from_volume: true
        volume_size: "{{ master_volume_size }}"

